---
title: "Poweranalysis"
author: "CK"
date: "14/08/2020"
output: 
 bookdown::html_document2:
  fig_caption: yes
  toc: yes
  toc_float: true
  number_sections: false
 bookdown::word_document2:
 bookdown::pdf_document2:
   keep_tex: true
editor_options: 
  chunk_output_type: console
#always_allow_html: true
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
  encoding=encoding,
  output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
  
  
  
---

# Brief data summary
```{r setup, include=TRUE, message=FALSE, echo=TRUE}
library(tidyverse)
library(rcompanion)
library(pwr)
library(rstatix)

# Get some data
metadata<- readr::read_tsv("~/Documents/Study/LaTrobe/Research/phD/Milestone2_Field_Survey/M2_Bacteria/M2_Qiime_output_Bacteria2020run/metadata.tsv") 

# Change to your liking
metadata2 <- metadata[c(2:nrow(metadata)),c(1:length(metadata))] %>%
  tibble::rownames_to_column("spl") %>%
  dplyr::mutate_all(type.convert) %>%
  dplyr::mutate_if(is.factor, as.character) %>%
  tibble::column_to_rownames("spl")
 
# Mean dieldrin concentrations per paddock
options(knitr.kable.NA = '')
kableExtra::kable(metadata2 %>%
  group_by(Paddock) %>%
  get_summary_stats(D1517, type = "mean_se")) %>% kableExtra::kable_styling(full_width = F, position = "left",bootstrap_options = c( "condensed"), font_size = 11 )

# Mean dieldrin losses per paddock
# There is no standard error within each paddock - as the values for dieldrin loss were collected per paddock, not per sample
kableExtra::kable(metadata2 %>%
  group_by(Paddock) %>%
  get_summary_stats(Dloss, type = "mean_se")) %>% kableExtra::kable_styling(full_width = F, position = "left",bootstrap_options = c( "condensed"), font_size = 11 )


```

# Confidence intervals (bootstrapped)
```{r ce, include=TRUE, message=FALSE, echo=TRUE}
# Test normality of dieldrin concentrations n = 36
shapiro.test(metadata2$D1517)  # not normal

# Get bootstrapped confidence interval - this time for dieldrin concentrations per sample.
rcompanion::groupwiseMean(D1517 ~ 1, data = metadata2, conf = 0.95, digits = 3,
                          boot = TRUE, R = 1000)


# Group data by paddock and select dieldrin loss - n = 12
meandata <- metadata2 %>% group_by(Soil, Paddock) %>% summarise(Dlossmean = mean(Dloss))

meandata %>% group_by(Soil) %>% get_summary_stats(Dlossmean, type = "mean_se")

# Test normality of dieldrin loss n = 12
shapiro.test(meandata$Dlossmean)

# Get bootstrapped confidence interval of dieldrin loss per paddock
rcompanion::groupwiseMean(Dlossmean ~ 1, data = meandata, conf = 0.95, digits = 3,
              boot = TRUE, R = 1000)


```

# Power analysis with pwr package
```{r power, include=TRUE, message=FALSE, echo=TRUE}
# Calculate the number of samples needed to model Dlossmean (12 samples) with CN as predictor
# https://cran.r-project.org/web/packages/pwr/vignettes/pwr-vignette.html
# The effect size is the R2 of the model. the coefficient of determination, aka the “proportion of variance explained”
pwr.f2.test(u = 1, f2 = 0.5/(1 - 0.5), sig.level = 0.001, power = 0.8)
#n = v + u + 1
# n = 21 + 1 + 1 = 22 paddocks needed at an effec size of 0.5


# samples (n) needed for a rubust mean
#http://r-video-tutorial.blogspot.com/2017/07/power-analysis-and-sample-size.html
# n = ((2 x STD) / SE )^2
data <- metadata2 %>% group_by(Paddock) %>% summarise(Dlossmean = mean(Dloss), CNmean = mean(CN))
sum_stat <- data %>% rstatix::get_summary_stats(Dlossmean, show = c("mean", "sd", "se"))
n = ( (2 * sum_stat$sd) / sum_stat$se )^2
# n = 48 samples needed for the mean dieldrin loss  to be robust
n 
```

# Resample examples
Resample 1000x and calculate mean and std of dieldrin concentrations
```{r resampleexample, include=TRUE, message=FALSE, warning=FALSE, fig.width=17, fig.asp=0.4}
resample = 1000
measurement = 'D1517'

# The mean mean function
meanfunction <- function(df){
df %>% rstatix::get_summary_stats(measurement, type = "mean")  
}

# Function to randomly resample the mean 1000x with replacement and get a df with the mean of each resample
# Do this once as this takes time and do not repeat for histogram
listfunction <- function(df){
listdf <- replicate(resample, dplyr::slice_sample(df, n= n, replace = TRUE), simplify = FALSE) %>%
  lapply(., meanfunction) %>% 
  bind_rows  
return(listdf)
}

# Function to get a summary statistic of the mean
summaryfunction <- function(listdf){
  listdf %>% rstatix::get_summary_stats(mean, type = "common")
}


# Function to get a historgram of the means
histofunction <- function(summarydf){
plotting <- summaryfunction(summarydf)
  summarydf %>% ggpubr::gghistogram(x= "mean", title = paste(resample,"x resampled with n =", n, ", mean =", plotting$mean, "stdv =", plotting$sd))
}


# n=10
n = 10 # number of samples to resample every time 
summarydf <- listfunction(metadata2)
summaryfunction(summarydf)
p10 <- histofunction(summarydf)

# n=15
n = 15 # number of samples to resample every time 
summarydf <- listfunction(metadata2)
summaryfunction(summarydf)
p15 <- histofunction(summarydf)

# n=20
n = 20 # number of samples to resample every time 
summarydf <- listfunction(metadata2)
summaryfunction(summarydf)
p20 <- histofunction(summarydf)

ggpubr::ggarrange(p10, p15, p20, nrow = 1)
```

